### ISSUE TITLE
Screenshot Processing

### ISSUE THREAD

**Issue by lenasong** [huntallcott/PhoneAddiction#10]
I don't see a way to validate screenshots in Qualtrics other than making sure the file uploaded is a photo. 

@gentzkow can we get the image processing team from India to help on validating the screenshots every week and digitizing them for the pilot? 

Note that the information on Screen Time is a lot richer than battery usage screen, and part of it is in bar graph form (breakdown of app usage on each day of the past week into categories) and will require more sophisticated programming to turn into numbers. For the purpose of our pilot, I think it's enough to get the total app usage and usage by category - these are displayed in weekly totals and can be easily extracted. We could find a developer down the road for the full experiment to extract any other additional information.

**Comment by gentzkow** [comment]
Hi @lenasong. There are a couple of options. 

1. In the past, we have worked with firms like [Hi-Tech](https://www.hitechos.com/) that provide business outsourcing services. Once upon a time they were quite inexpensive and high quality. I haven't worked with any of these companies for a while and so I don't have a good sense of which specific companies / countries are best at this point. If we went this route we'd want to shop around and get a bunch of quotes.

2. More recently, we have had success with digitization on Upwork. [Mike Sinkinson](https://som.yale.edu/faculty/michael-sinkinson) has been managing that effort, getting a bunch of historical cost records digitized. He would be the best person to talk you through optimal strategies, and he might also have a good sense of the pros and cons of Upwork relative to the outsourcing route.

**Comment by lenasong** [comment]
Quick update - I've reached out to several data entry firms as Mike suggested and heard back from 3 after sending a sample of our input and specifying required output. All of them suggest that the screenshots will be processed partially manually and their firms do not have the capability to fully automate this.

Quotes received so far (Hitech agrees to process 50-100 participants from the pilot and will provide a quote then):

- Data Entry India - $0.20 per participant every week (for about top 60 apps used). Very good quality 
- Flatworld Solutions - $0.56 per participant every week. Had to correct mistakes in a sample I sent them with only 2 participants 

So the cheaper option would cost us 20k+. I'm negotiating the price with them and they could possibly do cheaper if we have fewer screenshots per participants (One idea here is to ask participants to upload all app usage over 1 minute, but only get the company to process apps with 5 minutes or longer).
 
Before we decide whether to go with outsourcing data entry, how easy is it for someone to develop an image processing program like the one used in the moment app? Would conversation with someone at Moment be helpful?

Let me know what your thoughts are on this and whether we should spend more time looking into developers. In any case, as we proceed with the pilot I'll have a better sense of the speed and quality of these companies.

**Comment by gentzkow** [comment]
Thanks @lenasong. This sounds good. I definitely think something like only recording apps with 5min+ could be a good idea. 

I suspect building a tool to do the detection automatically will either be less reliable or more expensive (or both). But I could be wrong.

**Comment by lenasong** [comment]
Here's an overview of all the companies I've reached out to who have done some screenshot processing for us:
- Om Data Entry India - $0.17 per participant every week (for about top 60 apps used). Very good quality on small sample, baseline screenshot completed with errors
- Flatworld Solutions - $0.56 per participant every week. Had to correct mistakes in a sample I sent them with only 2 participants 
- Invensis - $0.56 per participant every week. Baseline screenshot completed with errors 
- Hi-tech - $0.016 per cell -> more than $0.70 per participant every week. Baseline screenshot completed with errors 

All of these are found via Google search for "Data entry outsource". I sent the baseline to Om, Invenesis and Hi-tech and did a training skype call with the cheapest option Om Data Entry India this morning, and asked Om to redo the baseline data entry. 

Since one option is significantly cheaper than the others, I'm thinking we should try Om Data Entry out to process rest of the pilot, and pay on a weekly basis. @gentzkow @huntallcott yes? 

Here's a [link](https://www.dropbox.com/sh/owz10zrl049vkx1/AAAZ29jYtqfdvEnm2PZnVROia?dl=0) to the input files that I'm sharing with the company, with a template for the output file we are requesting. 

Take a look. For the past 24 hour and past 7 day summaries with [bar graphs](https://www.apple.com/newsroom/images/product/os/ios/standard/ios12-screen-time_06042018_big.jpg.large.jpg), I feel there is a lot more information than what the data entry firm is able to extract. So far I tried to incorporate two outcome variables by asking the company to code these two answers from the past 24-hour graph: 
- Does the user have activity between 11 PM - 7 AM 
- What's the time for peak use in the past 24 hours (highest bar)

Should we omit these type of questions with data entry and try to find a developer later to process these graphs? If not, any additional questions you'd like to include?

**Comment by huntallcott** [comment]
@lenasong many thanks. My opinion would be that we should only get the required info to implement the incentive payments and compare to the elicited beliefs about usage. Can you confirm that these can be done without reading the graphs? If so, then I would be OK not coding the graphs.

The only reasons to code the graphs would be if:
1. We need those data to evaluate the MPLs and belief questions
2. You care about the two bullet questions you wrote above (I don't, they seem like they are just nice to know/gravy).
3. We want to develop the capability to read figures for some other reason that I might not be foreseeing.

Thanks again for making this happen.

**Comment by gentzkow** [comment]
Great. Thanks @lenasong. I agree with @huntallcott. 

I'm fine going ahead with a larger scale test with Om. Two things I've found helpful in the past:
(i) Make clear that we will check a random sample for errors and pay only if error rate is below some low threshold.
(ii) Have them enter each screenshot twice independently and reconcile discrepancies on their side before sending to us.

**Comment by lenasong** [comment]
@huntallcott @gentzkow thanks for the quick feedback. I'll communicate those points with Om when they get back to me with a final quote. 

Yes - the average daily use for the past 7 days and weekly total for categories are readily available.

**Comment by lenasong** [comment]
Quick update - I'm still negotiating the contract with Om. They seem very reluctant

**Comment by lenasong** [comment]
@gentzkow @huntallcott I've gotten Om Data Entry to agree on our requirement of lower than 2% error rate via double data entry. For this, they are asking for $0.30 per user every week. 

This is still the lowest offer I've received.
- Are we still comfortable with this pricing? If so I'll proceed to drafting the contract with Om.
- Do we have the budget to hire a quality assurance contractor? I'm thinking we could hire one of the other data entry firms/freelancers to review a subset of these screenshots every week for quality assurance and incentivize them based on mistakes they find.

**Comment by huntallcott** [comment]
Thanks @lenasong.
We have about $247k for the whole project to allocate as we want. 
If they spend 5 minutes per user (including double entry) this is $3.60 per hour. 
It seems like you've talked with multiple firms and this is the lowest price, so great.

But I would hold off on signing a contract until we are more certain about sample size, number of weeks, the Northwestern app, etc. Does that make sense?
-Hunt

**Comment by lenasong** [comment]
@huntallcott for sure! From what I hear from Shehnaz I don't think she can set up any payment without those details you mentioned. 

FYI - Om has sent me a [contract](https://drive.google.com/open?id=0BxK0VSkdFGoDNWNHcXRNV3BCTWNkaVloSTVQbmcwMXdPVE1v) draft, to be signed by Stanford. It doesn't specify scope of work and is paid per entry basis. I'll also get them to add the minimum error clause. The approval process by Stanford will take around 3-4 weeks, so I'll just pay them personally for their work on the pilot.
