### ISSUE TITLE
Pilot2 Results

### ISSUE THREAD

**Issue by michael-butler1994** [huntallcott/PhoneAddiction#16]
@gentzkow @huntallcott @lenasong 

Here's a draft of the Pilot2 Results 
[1_17_2019_pilot2_sum_stats.pdf](https://github.com/huntallcott/PhoneAddiction/files/2769742/1_17_2019_pilot2_sum_stats.pdf)
For reference, here's a draft of the Pilot1 Results 
[12_8_18_pilo1_sum_stats.pdf](https://github.com/huntallcott/PhoneAddiction/files/2769745/12_8_18_pilo1_sum_stats.pdf)

A few things to note:
 - The Pennyworth use data may need to be adjusted. I'm still working with American Chris to verify that I calculated daily phone usage correctly and to resolve a discrepancy in their app dashboard usage stats. In general though, Pennyworth data has been easy to work with. Once we verify the accuracy of our phone use calculations, I'll add an analysis on gaming detection to the report.
 - Antisocial has serious data quality issues, and they have struggled/failed to complete a few tasks we asked from them. When we first began working with Antisocial, I asked them to produce an exportable data set which contains the following columns: ParticipantID, day - hour, App, Use (minutes). So, for a given hour of a day, we could see how much time a given user was using a given app. After several emails/phone calls for re-explanation, they could not produce this dataset for us. Instead they produced a myriad of other datasets which contradicted each other (I.e. the daily phone use for a user was not equal across reports). Due to their data quality issues, we're not sure if it’s worth asking for their user data or asking further about their app blocking tech. It may be worth providing them with a bunch of feedback, asking them to clean up their data processing pipeline, and then asking for user data-- it's in their best interest, after all.

Let me know if you have any questions or if you would like me to look into something further.

**Comment by huntallcott** [comment]
@michael-butler1994, thanks for doing this!!! Fantastic.
1. I especially appreciated your short bullet points interpreting the tables and comparing the results to the results in Pilot 1. Table 16 is a nice idea, as is Figure 2 – I appreciate how you’re seeing how the quantitative/WTA questions should match up to the “qualitative” questions.
2. It looks to me like things went pretty well, e.g. the apps weren't gamed, people liked the apps, they understood the MPLs, people seemed like they thought our money would cause them to reduce usage, etc. Would you agree? What would you say are the main problems, if any? Please do update us ASAP on gaming/accuracy and how well you think Pennyworth worked. One thing that was alarming is that perceived use >> actual use.
3. In Section IX, Figure 1, shouldn’t the blue line in principle be below the pink line, or am I mis-understanding?
Thanks again. 

Also, I just talked with Lena. Let's make the case ASAP as to whether we should push forward into an experiment this semester.

**Comment by gentzkow** [comment]
Thanks @michael-butler1994. I agree that this is an outstanding writeup. Super clear. I really appreciate the bullet summaries in addition to the figures / tables.

I also had the general impression that things went well and that we basically have a design that works.

* I found the big mean differences in usage + perceptions between pilot1 and pilot2 surprising. It's possible it is just Android vs. iPhone as you say, but I wouldn't have had any reason to expect such a gap. Do we think it's possible that it's a difference in measurement? (I realize there's the issue you flag w/ usage in browsers for social.) Could there be some kinds of activity that our apps are missing but screentime is picking up -- like being on the phone or texting / reading notifications on the lock screen for example?

* Another odd thing was that total usage went way up in the Pennyworth social treatment group even as social usage went down (Table 10).

* I was a bit unsure how to map the summary of amount earned back to how well people complied with the restrictions. Is what the restriction groups were paid just 50 - 10*[post_ numbers shown in Tables 11 and 12]? So, for example, the median Pennyworth user in the general treatment earned 50 - 10*(3.15) = $18.50 and the median Pennyworth user in the social treatment earned 50 - 10*(0.28) = $47.20?

* Are we worried that people might game the social treatment by using Instagram etc. in their browsers? Can we see what other (non-social) apps they spent their time on? Would be interesting to see how those respond and actually produce measures of substitution.

* Do we think it's worth doing a statistical test of the effect of incentives on usage?

**Comment by michael-butler1994** [comment]
@huntallcott @gentzkow @lenasong . I’ve updated the results slightly: I corrected a typo on the Perceived minus Actual Use table (all results had to be multiplied by -1), and I categorized a few additional apps as social media for Pennyworth, causing social media use to increase in the results. Here are the new results: 
[1_23_19 Pilot 2 sum stats.pdf](https://github.com/huntallcott/PhoneAddiction/files/2789723/1_23_19.Pilot.2.sum.stats.pdf)
Here are a few answers to your questions:

**General Success from the Pilot:** 
 - Aside from a few minor details we have to sort out, Pennyworth accurately measures Phone Use, and only requires minor updates for the full experiment. 
 - I think American Chris is really good at what he does and is honest about his personal limitations and the app’s limitations (unlike Australian Chris :/ ).
 - We found no evidence of detectable gaming: I estimate that pennyworth participants had pennyworth actively tracking their phones about 99% of the time that their phones were on during the experiment. 

**General Concerns from the Pilot:** 
 - American Chris is really busy and takes a while to get back to us.
 - We will never be able to directly detect what websites participants visit on their mobile browser, with Pennyworth (or with any 3rd party mobile tracking app). Therefore, we cannot detect if a user scrolls through facebook or instagram on their mobile browser.
 - I'm not an expert on the identification strategy, but would it be worth rescaling the payment formula for the social media treatment group, given that the median use is 1.1 hours per day?

**Things Lena and I plan to do in the next few days (in order of priority)**
 - Think more about why perceived usage >> actual usage (tomorrow)
 - Outline the steps we would need to take to launch the full experiment in a week or so. (tomorrow/saturday)
 - Chat with Chris (Monday)
 - Research desktop browser trackers and lightweight apps that can implement hard controls
 - Add a table describing the daily usage distribution for all apps that have significant use (similar to table 16 in the pilot 1 results), for pennyworth users. Investigate substitutability. 
 - Statistical test on the treatment effect. 
 - Provide a detailed explanation of our gaming detection algorithm
 - let us know if we should addd anything to this list!

**MPL Comprehension and Section IX, Figure 1:**
 - In general, I think participants understand the MPL questions -- when the fixed payment reward was higher, more participants choose option A. However, I don’t think their choices exactly reflect their true preferences, partially because they didn’t completely understand exercise, as shown in Section IX, Figures 1 & 2. In these figures, we would expect the redline to never be greater than the blue line, since reducing social media by X minutes takes less effort than reducing general phone use by X minutes, regardless of the Option A payment. But as these graphs show, for a given payment, some people choose Option A in the social media MPL and Option B in the general MPL (I double checked this in the raw data as well). To prevent people from filling the MPL’s inconsistently in the full experiment, we could raise an error if a user chooses Option A for the social media MPL and Option B for the general MPL, for a given payment. 
 - In addition, for the basic MPL competency question we gave in the endline, described in tables 34 and 35, only 75% of participants selected the correct answer. Perhaps some participants rushed through the question.

**General Use Discrepancy between Iphone (pilot 1) and Android use (pilot 2) :** The median daily overall phone use for iphone users was 4.12 hrs, compared to 3.15 hrs for android users. Explanation(s) for the discrepancy:
 - Apple Screentime overestimates overall phone use: Like Pennyworth, Apple Screentime only tracks usage when the screen is on. Recall that Apple Screentime breaks a user’s phone use down by categories. In pilot 1, we found that the sum of phone use by category is about 30% less than the phone use that Apple Screen time reports overall. This likely occurs because some use is not categorized: e.g. use in the settings app or homescreen, though we’re not totally sure what use isn’t categorized. By contrast, I estimate that categorizable android app use is only 12% less than total android use, according to Pennyworth data. Perhaps then, Apple screentime overestimates iphone use by 18%! Also, according to this unanswered apple support question (which has been upvoted 73 times), the sum of use by app is significantly less than overall use. Given all of this, I’m inclined to think that Pennyworth more accurately measures Android use than Apple Screen Time measures iPhone use. 
 - It's also worth noting that androids and iphones take the same amount of time to "go to sleep", i.e. the amount time the screen remains on after a period of active use . Lena and tested this. 

**Social Media use Discrepancy between Iphone (pilot 1) and android use (pilot 2):** The median daily social media use for an iPhone user was 1.83 hours, compared to 1.10 hours for a Pennyworth user. Explanation(s) for the discrepancy:
 - Mobile Browsing: Apple Screentime tracks social media use on Safari, while Pennyworth cannot track social media use on Chrome (or any other browser).
 - Uncategorized Android Social Media Apps: There may be a few additional apps that we still need to categorize as a social media. Categorizing apps on Android is more challenging because different android phones have different built-in calling, texting, and homepage apps. We have to check in with Chris, but there may be one android model with an app that functions as a texting, calling, and homepage app. For this reason, we could remove texting and calling apps from the social media category.

**Surprising result from Table 10**
 - In table 10, I checked for any bugs in the pre and post treatment general use calculation, and could not find any. As @gentzkow said, the increase in general use for the 2 pennyworth users in the social media treatment group is surprising. This could also be indirect evidence of gaming: to continue using their social media apps, these participants used their browser. 

**Payout Analysis Clarification**
@gentzkow, yes you have it right.

**Comment by gentzkow** [comment]
Thanks! All very clear.

Sounds like full steam ahead on this basic design using Pennyworth.

I do think we want to rescale payments based on what we learned here.

**Comment by michael-butler1994** [comment]
Here’s an attempt to explain why Perceived Use >> Actual Use in Pilot 2. To summarize, pilot 2 perceived use is only greater than actual use at baseline. This baseline discrepancy is likely due two stories: 1) participants considered phone calls and listening to music as use while pennyworth/antisocial do not; 2) either participants overestimate their use or pennyworth/antisocial underestimate use. At midline, participant beliefs conform to their use stats. If anyone else has any thoughts, I'd love to hear them. 

First, it’s worth noting that Pilot 2 participants only overestimated their actual use at Baseline. According to the last subtable in Table 13, the median difference between perceived and actual use at baseline was 1.95 hours, while at midline, the median difference was only -0.33 hours. The estimation correction from baseline to midline has 4 potential explanations:

1. **Actual use increased _and_ beliefs decreased**: Median perceived use decreased from 5.00 hours at baseline to 3.75 hours at midline, and actual use increased from 2.34 hours in pre-treatment to 3.08 hours in post-treatment (table 13).

2. **More information:** At the beginning of the midline survey, we display the participant’s use stats from the pre-treatment period. These use stats could inform their beliefs.

3. **Phone Use definition discrepancy:**  The pennyworth phone use calculation only counts use when the screen is on. So, when someone talks on the phone or listens to music while the screen turns off, we do not count this as use. If these participant factored these activities into their baseline beliefs, we would expect perceived use >> actual use, holding all else equal. For this story to explain a 100% of the difference between perceived use and actual use at baseline we would have to assume that our participants chat on the phone and listen to music, screen off, for around 2 hours every day, which seems plausible. Once participants saw their use stats during the midline or while checking their app, their beliefs likely then conformed to the use stats. In the full experiment we should provide a clear definition of phone use (like we did in the baseline-- see below).

4. **Survey phrasing**: In both baseline and midline surveys, we asked participants to estimate their average daily use using the following question:
![screen shot 2019-01-24 at 4 32 57 pm](https://user-images.githubusercontent.com/35438895/51714750-41f45380-2004-11e9-92af-93c8ad7b3501.png)
 - This language could lead to inflated beliefs because:

    - The pre-treatment period occurred before the holiday period, during NYU’s exam week, so if participants planned to use their phone for more time during the holiday period, then we would expect perceived use (holiday period) >> actual use (pre-treatment period).
     - Perhaps some participants thought we were asking them to estimate their total usage over the December 22-January 6 time period. 
    - I don’t actually think these two explanations hold much weight because of answers participants provided to an earlier question in the baseline: “About how much time per day on average do you think you use your phone? Note: please enter whole numbers. For example, if you think you use your phone for X hours and Y minutes a day, put X in the hours box and Y in the minutes box.” This question yielded a very similar distribution of answers as the question above (the mean and median answers were both also ~5 hours). 
 
To summarize, it’s plausible that participants were able to correct their inflated beliefs at baseline after we displayed their pretreatment use statistics. **But, why were baseline beliefs so inflated in the first place? Further, why would the median pilot 2 user think their daily phone use would be 5 hours a day, compared to the median pilot 1 participant at baseline who believed their use to be only 2.75 hours a day?** A few potential explanations:

1. **Different Survey phrasing**: take a look at the belief survey question from pilot 1:
![screen shot 2019-01-24 at 5 10 16 pm](https://user-images.githubusercontent.com/35438895/51714768-51739c80-2004-11e9-9e01-3a34f7b73d4e.png)
   - We asked pilot 1 participants to estimate their use in minutes. Since math is hard, participants could bias their answers downwards. e.g., if you use your phone for 4.5 hours, it’s hard to calculate and enter 270 minutes, and I bet participants were inclined to round down to 200 or 240, than round up to 300. Pilot 2 belief stats are like biased upwards, on the other hand, because we did not provide a clear definition of phone use, as I describe above.

 2. **Pennyworth underestimates usage, and participants were accurately guessing their avg. daily usage at baseline:**  This could be the case, but it’s worth noting Antisocial and Google Well-Being under report use stats compared to Pennyworth. Also, in my previous post, I explained that we measured Pilot 1 participants spending more time on their phone compared to pilot 2 Pennyworth users because Apple Screentime overestimates phone use. All this is to say that, I’m pretty confident that Pennyworth accurately measures use. 

3. **Sample Selection Bias**: Perhaps, the participants filling out the baseline were concerned about their phone use before the experiment and their concern was reflected in their inflated baseline beliefs. However, the opposite holds true: participants that think they use their phone too much tend to believe they use their phone less: 
![screen shot 2019-01-24 at 5 45 02 pm](https://user-images.githubusercontent.com/35438895/51714787-5cc6c800-2004-11e9-95b2-bd97fda34ffa.png)

**Comment by huntallcott** [comment]
Thanks @michael-butler1994, this is very interesting, and very important for us to be thinking about how we word the surveys and what we're measuring. So many thanks.
Comments, mostly just repeating what you said:
1. It seems clear that initial uncalibrated beliefs shouldn’t be used as a measure of whether people over-or under-estimate use.
2. I think that the pennyworth definition using “screen on” is conceptually  the right thing for us to incentivize, by which I mean the thing most likely to conceptually reflect the concerns that people have about smartphone over-use.

**Comment by gentzkow** [comment]
Thanks @michael-butler1994. I agree w/ @huntallcott's comments.

I would add that we probably want to make even more clear to people that phone use, listening to music, etc. are *not* included in the time if the screen is off.

**Comment by michael-butler1994** [comment]
@huntallcott @gentzkow @lenasong 
Here's an updated version of the pilot 2 results. 
[1_28_19_pilot2_sum_stats.pdf](https://github.com/huntallcott/PhoneAddiction/files/2804172/1_28_19_pilot2_sum_stats.pdf)

This updated version contains:
- **Use by App for Pennyworth users** (table 15). The only disconcerting takeaway is that launcher app use varies significantly by phone model, but this may have occurred by random chance -- several launcher apps have only 1 user. We'll ask Chris about it later this afternoon.
- **Pilot 2 interview results** (Section XIII). I conducted 3 interviews with pennyworth users. None revealed any worrisome inaccuracies in pennyworth. I interviewed one international student who has two phones, so we could consider limiting the study to non-international students, unless we allow participants to register two phones, which could slightly complicate data management.

**Comment by huntallcott** [comment]
Thanks @michael-butler1994,
One quick follow-up. @gentzkow was interested in knowing: "Do we think it's worth doing a statistical test of the effect of incentives on usage?"
It looks like people say they expect that the incentives would have a big impact, and I'm also pasting below the descriptive results table:
![image](https://user-images.githubusercontent.com/23505296/51857151-8aab5580-22ff-11e9-9332-2dca4d142eaf.png)
 
I think that this issue will be relevant for our meeting, as we determine what type of restrictions we want to impose. @michael-butler1994 is it easy, before our meeting, to run this regression:

RestrictionPeriodPhoneUse = \tau * 1(Either Social or Overall Phone Use Restriction Group) + \rho * BaselinePeriodPhoneUse,

with one observation per person, using both Penniworth and AntiSocial (unless you don't trust the Anti-Social data at all)?
And then post the Stata results here or in the pdf?

**Comment by michael-butler1994** [comment]
not pretty, but i think it's correct. 
![screen shot 2019-01-28 at 2 00 53 pm](https://user-images.githubusercontent.com/35438895/51859469-31462500-2305-11e9-9115-818e79c51861.png)

**Comment by huntallcott** [comment]
got it. 
1. so to me this says that we may be getting some reduction of between 0 and 1 hours per day, but we can reject reductions of more than 1 hour per day. is that correct?
2. i also think this means that people don't reduce their usage as much as they predict they would reduce their usage in the belief elicitation questions, correct? 
3. related to (2), can you try one more thing: instead of treat_bool, have treat_bool * predicted hours reduced, where predicted hours reduced = baseline hours * predicted percent reduction under the price incentive. then also add a control for predicted hours reduced. the coefficient on treat_bool * predicted hours reduced should be a test of (2) under a zero measurement error assumption. this would also give us higher power in a first stage where we look at impacts on SWB and any other outcome.

**Comment by michael-butler1994** [comment]
@huntallcott take a look section 5 "Statistical Test on Outcomes Interests" in this updated report. 
[1_30_19_pilot2_sum_stats.pdf](https://github.com/huntallcott/PhoneAddiction/files/2813689/1_30_19_pilot2_sum_stats.pdf)

Short responses:
 - 1: we can reject reductions of more than 1 hour per day, depending on model specification. check out table 17.
 - 2 and 3: Yes, it seems that participants do not fully follow through on their _general_ phone use reduction predictions. For social media use, it's unclear if participants fully follow through on their reduction predictions. Given the large standard errors on relevant coefficients, I don't think we can draw any conclusions with high confidence. Check out table 18.
