### ISSUE TITLE
Lit Review

### ISSUE THREAD

**Issue by KellyBuckley** [huntallcott/PhoneAddiction#2]
Review media lit on this type of question, make list of major/common that may not have been tested experimentally

**Comment by KellyBuckley** [comment]
I've added the lit review to the dropbox under PhoneAddiction\Literature\CommLitReview -- there are notes with the citations (not perfectly formatted) and the review. It's mainly drawn from the communications and media studies literature with some psychology. I outline some of my general thoughts in it based on what I read, but I'm sure they aren't perfectly thought out so I'd be happy to discuss. I also have the pdfs of the papers in Zotero but if it would be helpful I can export them to a dropbox folder (or share the Zotero folder if anyone uses that).

**Comment by gentzkow** [comment]
Thanks @KellyBuckley. This is helpful.

What I didn't get a clear sense of from the review is exactly what kinds of empirical + experimental evidence exist on the effects of smartphone use, whether people are addicted, etc. I wonder if it might be helpful to divide things by methodology -- e.g., surveys asking peoples' subjective assessments directly, analysis of cross-sectional or longitudinal correlations (like Twenge), randomized lab experiments, and randomized field experiments -- and then try to produce a comprehensive summary of studies in each category. Do you think that might be feasible / helpful?

**Comment by KellyBuckley** [comment]
@gentzkow makes sense, yes I can work on that, I think it would be helpful.

**Comment by KellyBuckley** [comment]
Wanted to update that I haven't forgotten about this, have just been busy with other projects, but will try and get to it soon

**Comment by KellyBuckley** [comment]
I've added PhoneAddiction\Literature\CommLitReview\lit_review_by_methodology.docx to the dropbox. This is just a broad overview of the papers I looked at sorted into what type of investigation they did. Since I was primarily looking at media studies/communication/psychology, there aren't any randomized experiments. 

I think we still want to pull this together with the other lit review docs in the dropbox which cover Twenge, etc. and do a more comprehensive review. I can also do that but since I haven't done a lit review before I'm not sure exactly what it should look like. Do you all have any examples?

**Comment by huntallcott** [comment]
closing this for now
