### ISSUE TITLE
Pilot3 Recruitment Ad

### ISSUE THREAD

**Issue by michael-butler1994** [huntallcott/PhoneAddiction#20]
@lenasong Here are the specs I would recommend for the recruitment ad:
 - Use the filters described [here](https://github.com/huntallcott/PhoneAddiction/issues/19#issuecomment-476913178)
 - Use the pictures below
 - drop "phone use" in the ad text

![chatting-cups-dog-745045](https://user-images.githubusercontent.com/35438895/55084424-8d19f980-507b-11e9-8adf-03e1fba8a2c8.jpg)
![backpacks-college-college-students-1454360](https://user-images.githubusercontent.com/35438895/55084434-91dead80-507b-11e9-82f4-272bbc18081d.jpg)

**Comment by lenasong** [comment]
thanks @michael-butler1994! 
Here's one of the ads (there are 5 other ones with different photos):
![image](https://user-images.githubusercontent.com/38102116/55123842-8cfd1680-50da-11e9-8a21-f04ac2fed174.png)
