### ISSUE TITLE
Well-being survey questions

### ISSUE THREAD

**Issue by KellyBuckley** [huntallcott/PhoneAddiction#3]
The well-being questions we have now are somewhat randomly pulled from the Monitoring the Future study. Realized working on the facebook project, though, that for well-being scales to actually measure something you need to do the complete scale. It seems worth figuring out what aspects of well-being we care about and using the standard scales. I've created a [google doc](https://docs.google.com/document/d/1yb_B3BAiWHDkLeTwN5tkfLhFu1p6lRZDzqXLLf8F8cM/edit?usp=sharing) with the ones used in Burke, M., & Kraut, R. E. (2016). The Relationship Between Facebook Use and Well-Being Depends on Communication Type and Tie Strength. which seem pretty standard. Thoughts?

**Comment by lenasong** [comment]
@KellyBuckley thanks for the lit review! Our final SWB questions are incorporated in [survey instrument](https://docs.google.com/document/d/1zb_x73LLjkU-TqPGcUHrS6ULYx-dPwCxV23nkPo4yCA/edit?ts=5c913465).
