### ISSUE TITLE
Participant Payments

### ISSUE THREAD

**Issue by lenasong** [huntallcott/PhoneAddiction#9]
For the short survey I paid participants using Amazon gift card. Rewards Genius seems ideal for the full experiment since it presents a range of options participants can choose from and we can collect data on whether the rewards are claimed and what cards they choose. I'm indifferent between these two options for the pilot and will go with whatever is easier to set up (depends on our sample size) unless anyone has a strong opinion on this.  

Here's the current wording on payment:

> You will be paid $15 in total for completing the online surveys and weekly screenshots upload. This includes $5 for Survey 1 (paid right after you complete the survey) and a $10 completion payment at the end of the study. 

> There is a 1 in 3 chance that you may get the opportunity to earn an additional $30 (on average), paid to you after Survey 3, if you agree to complete an optional task proposed to you in Survey 2. 

> If you are determined to be eligible for the study, you will also be invited to refer friends and each referral gives you one entry into a draw for $1000. Your chance of winning is about 1 in 500.

Any additional changes to this payment scheme? 

As @huntallcott suggested in #8 [here](https://github.com/huntallcott/PhoneAddiction/issues/8#issuecomment-420096372), we will randomize over the completion payment and payment for recruiting friends. Are WTA payments with payment of $30 on average too high for 2 weeks of reducing phone usage?

**Comment by huntallcott** [comment]
@lenasong I think that this scheme is a good way to start and these numbers are also a good place to start.
In the pilot we will get a sense of the distribution of WTA. Using that information we can figure out more about whether an average of $30 is enough/too much/etc.
One thing: can you review the questions in the pilot and see if you think you have the best possible questions for predicting WTA to reduce phone usage? I think you should add some question around how much disposable income people have, or how strapped for cash they feel, along with questions around how much they think they use their phone. These two things should help us to predict WTA and could be used for price discriminating in the BDM mechanism as we had tried to do with the FB experiment.

**Comment by lenasong** [comment]
@huntallcott I've reviewed the pilot questions. They already contain the questions Kelly and I came up earlier - questions on gender, combined income from household (parents if dependent on them), zip code where they lived prior to NYU, average daily phone usage, average daily pick-ups.

I'm suggestion two additional questions (using standard questions from the College Senior Survey):

1. If you borrowed money to help pay for college expenses, estimate how much you owe as of June 30, 2018. [Enter an amount]

2. How much of the past year’s educational expenses (room, board, tuition, and fees) were covered from each of the following sources? 
- Family resources (parents, relatives, spouse, etc.)
- My own resources (income from work, work-study, etc.)
- Aid which need not be repaid (grants, scholarships, military, etc.)
- Aid which must be repaid (loans, etc.)
Choose from 
- $15,000 or more
- $10,000 to 14,999,
- $6,000 to $9,999
- $3,000 to $5,999
- $1 to $2,999
- None

Let me know what you think. These questions give a sense of liquidity, % of earned vs. money received from other sources, and total educational expenses. Students would have a sense of these numbers when they pay for tuition etc every semester.

We could also add questions about what their total expenses (food, entertainment, etc) are, but I'm not sure how precise and/or accurate the response is from the average student.

**Comment by huntallcott** [comment]
Thanks Lena. Am I right that these questions are to help us with price
discrimination in the bdm?
If so, I would propose we do something simpler. What if you either just ask
a qualitative likert question, eg how tight is your financial situation
these days?
Fine, moderately tight, very tight etc.

These questions you proposed are precise in some sense but are probably
more noisy for our purposes than what I’m proposing.

Then after this let me know and I’ll review the whole survey?
-- 

Hunt Allcott

https://sites.google.com/site/allcott/home

**Comment by lenasong** [comment]
@huntallcott sounds good. I'm adding two questions: one about financial situation now that you are proposing and one about general ability to finance their education - taken from CIRP Freshman Survey. (As a grad student I would always say that my financial situation is very tight when asked generally, hence the additional question - feel free to change on qualtrics as you see fit).

I'm creating a screenshot upload survey focusing on iPhones only for now with updated instructions for Screen Time. Will let you know when the surveys (recruitment, baseline, and screenshot upload) are ready for review.

**Comment by lenasong** [comment]
I've set up Rewards Genius for participant payment and just paid our 16 pilot finishers (for completion of all surveys, friend invites and treatment incentives) via a single Tango Card.

A summary of deposits and withdrawals from the account can be found in Tango Card Account Overview, under Dropbox\PhoneAddiction\Survey Logistics\Tango Card.

**Comment by huntallcott** [comment]
Awesome, thank you.
Can you confirm that if you're using my credit card, you'll make sure that the reimbursement gets processed?

**Comment by lenasong** [comment]
@huntallcott yes, and this one is all set up directly with Stanford!
